title = "aignas blog"
base_url = "localhost"
description = "Personal experiences whilst travelling through the geekdom of tech"
compile_sass = true
check_external_links = true
generate_rss = true
taxonomies = [
  {name = "tags"},
  {name = "categories"},
]

[markdown]
highlight_code = true
highlight_theme = "monokai"
render_emoji = true
smart_punctuation = true

[extra]
# Put all your custom variables here
domain = "localhost"
copyright = "2017&mdash;2023"
twitter = "anikevicius"
github = "aignas"
name = "aignas"
author = "aignas"
paginate_path = '/blog/page/:num/'
