title = "aignas blog"
base_url = "https://anikevicius.lt"
description = "Personal experiences whilst travelling through the geekdom of tech"
compile_sass = true
highlight_code = true
highlight_theme = "base16-ocean-dark"
check_external_links = false
generate_rss = true
taxonomies = [
  {name = "tags"},
  {name = "categories"},
]

[extra]
# Put all your custom variables here
domain = "anikevicius.lt"
copyright = "2017&mdash;2023"
twitter = "anikevicius"
github = "aignas"
name = "aignas"
author = "aignas"
paginate_path = '/blog/page/:num/'
